FROM golang:1.24-bullseye
WORKDIR /app
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /go/src/github.com/dev-helper/dev-helper
VOLUME [ "/go/src/github.com/dev-helper/dev-helper" ]
ENTRYPOINT ["dlv", "--headless", "--listen=:40000", "--api-version=2", "exec", "./dev-helper"]
